version: '3'

services:

    nginx:
      image: nginx:alpine
      build:
        context: ./docker/nginx/
        dockerfile: ./Dockerfile
      container_name: nginx
      volumes:
        - .:/var/www/html:ro
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80
        - 443:443
      depends_on:
        - backend

    backend:
      image: php:latest
      container_name: backend
      build:
        context: .
        dockerfile: ./Dockerfile
      restart: always
      volumes:
        - .:/var/www/html
      expose:
        - 9000
      depends_on:
        - mysql

    mysql:
      image: mysql:8.0
      container_name: mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        - MYSQL_ROOT_PASSWORD=asdf
        - MYSQL_DATABASE=mydb
      ports:
        - 33062:3306
      volumes:
        - ./var/mysql-data:/var/lib/mysql
        - ./docker/mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql


    adminer:
      image: adminer:latest
      container_name: adminer
      restart: always
      ports:
        - 8080:8080
